project_id = "kvmvekesxdzwodnfabdr"

[auth]
site_url = "https://healthzone.mgm.zone"
additional_redirect_urls = [
  "https://healthzone.mgm.zone",
  "https://healthzone.mgm.zone/**"
]

[auth.email]
enable_confirmations = true

[auth.email.smtp]
enabled = true
host = "smtp.resend.com"
port = 465
user = "resend"
pass = "env(SUPABASE_AUTH_SMTP_PASS)"
admin_email = "healthzone@mgm.zone"
sender_name = "HealthZone"

[auth.email.template.confirmation]
subject = "Confirm your HealthZone email"
content_path = "./supabase/templates/confirmation.html"
