// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvmvekesxdzwodnfabdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2bXZla2VzeGR6d29kbmZhYmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2OTI5NzYsImV4cCI6MjA1NzI2ODk3Nn0.5BYKCiwX_kctm6iYU_zfs4gyytpLhcml5Q53LvGCY9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);